/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilBug {
    }
}
declare global {
    interface HTMLStencilBugElement extends Components.StencilBug, HTMLStencilElement {
    }
    var HTMLStencilBugElement: {
        prototype: HTMLStencilBugElement;
        new (): HTMLStencilBugElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-bug": HTMLStencilBugElement;
    }
}
declare namespace LocalJSX {
    interface StencilBug {
    }
    interface IntrinsicElements {
        "stencil-bug": StencilBug;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-bug": LocalJSX.StencilBug & JSXBase.HTMLAttributes<HTMLStencilBugElement>;
        }
    }
}
